<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MOVE Móvel</title>

    <!-- Sets initial viewport load and disables zooming  -->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">

    <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Include the compiled Ratchet CSS -->
    <link rel="stylesheet" href="/css/ratchet.min.css">
    <link rel="stylesheet" href="/css/ratchet-theme-ios.min.css">

    <!-- Include the compiled Ratchet JS -->
    <script src="/js/ratchet.js"></script>
    <script src="/js/push.js"></script>
  </head>
  <body>

  	<div class="content">
		<?php echo $this->layout()->content; ?>
	</div>

	<nav class="bar bar-tab">
	  <a class="tab-item active" href="/">
	    <span class="icon icon-home"></span>
	    <span class="tab-label">Início</span>
	  </a>
	  <a class="tab-item" href="/linhas">
	    <span class="icon icon-search"></span>
	    <span class="tab-label">Linhas</span>
	  </a>
	  <a class="tab-item" href="/horarios">
	    <span class="icon icon-info"></span>
	    <span class="tab-label">Horários</span>
	  </a>
	  <a class="tab-item" href="/avaliacao">
	    <span class="icon icon-star-filled"></span>
	    <span class="tab-label">Avaliar</span>
	  </a>
	  <a class="tab-item" href="/ajustes">
	    <span class="icon icon-gear"></span>
	    <span class="tab-label">Ajustes</span>
	  </a>
	</nav>
    

  </body>
</html>
